name: Docker Image CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Auth API image
      - name: Build and push Auth API Docker image
        run: |
          docker build -t mdnaseem/kub-auth:v${{ github.run_number }} -f auth-api/Dockerfile auth-api
          docker push mdnaseem/kub-auth:v${{ github.run_number }}

      # Build and push Users API image
      - name: Build and push Users API Docker image
        run: |
          docker build -t mdnaseem/kub-user:v${{ github.run_number }} -f users-api/Dockerfile users-api
          docker push mdnaseem/kub-user:v${{ github.run_number }}
